/**
 * Database Schema Types
 *
 * Auto-generated by MTPX CLI
 * Generated at: 2026-02-22T21:12:21.357Z
 *
 * DO NOT EDIT MANUALLY - Run 'mtpx db:generate' to regenerate
 */

export interface SystemSecrets {
  key: string;
  value: string;
  [key: string]: unknown;
}

export interface Categories {
  id: number; // default: nextval('categories_id_seq'::regclass)
  name: string;
  slug: string;
  parent_id: number | null;
  metadata: Record<string, unknown> | null;
  created_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

export interface KeystoreCredentials {
  namespace: string;
  service_type: string;
  name: string;
  data_json: string;
  source: string; // default: 'unknown'::character varying
  created_at: number;
  updated_at: number;
  expires_at: number | null;
  access_count: number; // default: 0
  last_accessed: number | null;
  [key: string]: unknown;
}

export interface KeystoreNamespaces {
  name: string;
  description: string | null;
  created_at: number;
  updated_at: number;
  [key: string]: unknown;
}

export interface OrderItems {
  id: string; // default: gen_random_uuid()
  order_id: string;
  product_id: string;
  quantity: number; // default: 1
  price: number;
  created_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

export interface Orders {
  id: string; // default: gen_random_uuid()
  user_id: string;
  status: string; // default: 'pending'::character varying
  total: number; // default: 0
  items: Record<string, unknown> | null;
  shipping_address: Record<string, unknown> | null;
  notes: string | null;
  created_at: string; // default: CURRENT_TIMESTAMP
  updated_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

export interface Products {
  id: string; // default: gen_random_uuid()
  sku: string;
  name: string;
  description: string | null;
  price: number;
  stock: number; // default: 0
  reserved_stock: number; // default: 0
  category: string | null;
  tags: Record<string, unknown> | null;
  status: string; // default: 'active'::character varying
  created_at: string; // default: CURRENT_TIMESTAMP
  updated_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

export interface Users {
  id: string; // default: gen_random_uuid()
  name: string;
  email: string;
  role: string; // default: 'user'::character varying
  status: string; // default: 'active'::character varying
  created_at: string; // default: CURRENT_TIMESTAMP
  updated_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

/**
 * Database Schema
 * Use with createTypedDatabase<Schema>(driver)
 */
export interface Schema {
  _system_secrets: SystemSecrets;
  categories: Categories;
  keystore_credentials: KeystoreCredentials;
  keystore_namespaces: KeystoreNamespaces;
  order_items: OrderItems;
  orders: Orders;
  products: Products;
  users: Users;
  [key: string]: Record<string, unknown>;
}

export default Schema;
