/**
 * Database Schema Definition
 *
 * Auto-generated by Multpex CLI (db:pull)
 * Generated at: 2026-01-26T00:48:08.549Z
 *
 * This file defines the database schema using the declarative API.
 * Run `multpex db:push` to apply changes to the database.
 */

import { Schema as S } from "@multpex/sdk-typescript";

// ============================================================================
// Table Definitions
// ============================================================================

export const categories = S.createTable("categories", {
  id: S.serial().primaryKey(),
  name: S.varchar(100).notNull(),
  slug: S.varchar(100).notNull(),
  parent_id: S.bigint().nullable(),
  metadata: S.jsonb().nullable(),
  created_at: S.timestamp().notNull().defaultNow(),
});

export const order_items = S.createTable("order_items", {
  id: S.uuid().primaryKey().defaultRandom(),
  order_id: S.uuid().notNull(),
  product_id: S.uuid().notNull(),
  quantity: S.integer().notNull().default(1),
  price: S.decimal(10, 2).notNull(),
  created_at: S.timestamp().notNull().defaultNow(),
});

export const orders = S.createTable("orders", {
  id: S.uuid().primaryKey().defaultRandom(),
  user_id: S.uuid().notNull(),
  status: S.varchar(50).notNull().default("pending"),
  total: S.decimal(10, 2).notNull().default(0),
  items: S.jsonb().nullable(),
  shipping_address: S.jsonb().nullable(),
  notes: S.text().nullable(),
  created_at: S.timestamp().notNull().defaultNow(),
  updated_at: S.timestamp().notNull().defaultNow(),
});

export const products = S.createTable("products", {
  id: S.uuid().primaryKey().defaultRandom(),
  sku: S.varchar(50).notNull(),
  name: S.varchar(255).notNull(),
  description: S.text().nullable(),
  price: S.decimal(10, 2).notNull(),
  stock: S.integer().notNull().default(0),
  reserved_stock: S.integer().notNull().default(0),
  category: S.varchar(100).nullable(),
  tags: S.jsonb().nullable(),
  status: S.varchar(50).notNull().default("active"),
  created_at: S.timestamp().notNull().defaultNow(),
  updated_at: S.timestamp().notNull().defaultNow(),
});

export const users = S.createTable("users", {
  id: S.uuid().primaryKey().defaultRandom(),
  name: S.varchar(100).notNull(),
  email: S.varchar(255).notNull(),
  role: S.varchar(50).notNull().default("user"),
  status: S.varchar(50).notNull().default("active"),
  created_at: S.timestamp().notNull().defaultNow(),
  updated_at: S.timestamp().notNull().defaultNow(),
});

// ============================================================================
// Schema Export (for db:push)
// ============================================================================

export const schema = {
  categories,
  order_items,
  orders,
  products,
  users,
};

// ============================================================================
// TypeScript Type Definitions
// ============================================================================

export type Category = {
  id: number;
  name: string;
  slug: string;
  parent_id: number | null;
  metadata: unknown | null;
  created_at: Date;
};

export type OrderItem = {
  id: string;
  order_id: string;
  product_id: string;
  quantity: number;
  price: number;
  created_at: Date;
};

export type Order = {
  id: string;
  user_id: string;
  status: string;
  total: number;
  items: unknown | null;
  shipping_address: unknown | null;
  notes: string | null;
  created_at: Date;
  updated_at: Date;
};

export type Product = {
  id: string;
  sku: string;
  name: string;
  description: string | null;
  price: number;
  stock: number;
  reserved_stock: number;
  category: string | null;
  tags: unknown | null;
  status: string;
  created_at: Date;
  updated_at: Date;
};

export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
  status: string;
  created_at: Date;
  updated_at: Date;
};

/**
 * Database schema type for use with createService<Schema>()
 */
export type Schema = {
  categories: Category;
  order_items: OrderItem;
  orders: Order;
  products: Product;
  users: User;
  [key: string]: Record<string, unknown>;
};

export default schema;
