/**
 * Database Schema Types
 *
 * Auto-generated by mtpx CLI
 * Generated at: 2026-04-08T22:23:47.962Z
 *
 * DO NOT EDIT MANUALLY - Run 'mtpx db:generate' to regenerate
 */

export interface Users {
  id: string;
  name: string;
  email: string;
  active: boolean; // default: true
  created_at: string; // default: CURRENT_TIMESTAMP
  updated_at: string; // default: CURRENT_TIMESTAMP
  [key: string]: unknown;
}

/**
 * Database Schema
 * Use with createTypedDatabase<Schema>(driver)
 */
export interface Schema {
  users: Users;
  [key: string]: Record<string, unknown>;
}
